# Run this non-default docker-compose file with:
#   docker-compose -f docker-compose.local.yaml up
#   or
#   docker compose -f docker-compose.local.yaml up
# 
# Stop this non-default docker-compose file with:
#   docker-compose -f docker-compose.local.yaml down
#   or
#   docker compose -f docker-compose.local.yaml down
# 
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./:/app
    env_file:
      - ./env/.env.development.local
    platform: linux/amd64

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    env_file:
      - ./env/.env.development.local
    volumes:
      - data:/data/db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
    
volumes:
  data: